// 默认视频编码分辨率
#define VIDEO_WIDTH_ENCODE_DEFAULT 320
#define VIDEO_HEIGHT_ENCODE_DEFAULT 240
// 默认视频采集分辨率
#define VIDEO_WIDTH_CAPTURE_DEFAULT 640
#define VIDEO_HEIGHT_CAPTURE_DEFAULT 480
// 默认userId
#define UID_DEFAULT -1
